2025-08-10 12:28:08,335 - ERROR - rexus.errors - ERROR
Message: Uncaught exception: IndentationError: unexpected indent (view.py, line 1181)
File: C:\Users\itachi\Desktop\martin\Rexus.app\rexus\utils\error_handler.py:24
Function: handle_exception
---
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\itachi\Desktop\martin\Rexus.app\rexus\modules\logistica\__init__.py", line 5, in <module>
    from .view import LogisticaView
  File "C:\Users\itachi\Desktop\martin\Rexus.app\rexus\modules\logistica\view.py", line 1181
    self.combo_vista_mapa = RexusComboBox()
IndentationError: unexpected indent
2025-08-10 13:47:24 - rexus.modules.mantenimiento.controller - [31mERROR[0m - Error cargando datos iniciales: 'MantenimientoView' object has no attribute 'cargar_equipos'
2025-08-10 13:47:24 - rexus.modules.mantenimiento.controller - [31mERROR[0m - Error cargando datos iniciales: 'MantenimientoView' object has no attribute 'cargar_equipos'
2025-08-10 18:17:05,442 - ERROR - rexus.errors - ERROR
Message: Uncaught exception: IndentationError: unexpected indent (view.py, line 207)
File: C:\Users\itachi\Desktop\martin\Rexus.app\rexus\utils\error_handler.py:24
Function: handle_exception
---
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\itachi\Desktop\martin\Rexus.app\rexus\modules\logistica\__init__.py", line 5, in <module>
    from .view import LogisticaView
  File "C:\Users\itachi\Desktop\martin\Rexus.app\rexus\modules\logistica\view.py", line 207
    try:
IndentationError: unexpected indent
2025-08-10 18:47:16 - rexus.modules.mantenimiento.controller - [31mERROR[0m - Error cargando datos iniciales: 'MantenimientoView' object has no attribute 'cargar_equipos'
2025-08-10 18:47:16 - rexus.modules.mantenimiento.controller - [31mERROR[0m - Error cargando datos iniciales: 'MantenimientoView' object has no attribute 'cargar_equipos'
2025-08-10 23:49:23,627 - ERROR - rexus.errors - ERROR
Message: Uncaught exception: UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
File: C:\Users\itachi\Desktop\martin\Rexus.app\.\rexus\utils\error_handler.py:24
Function: handle_exception
---
Traceback (most recent call last):
  File "<string>", line 37, in <module>
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
2025-08-12 08:58:50,474 - ERROR - rexus.errors - ERROR
Message: Uncaught exception: UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 10: character maps to <undefined>
File: C:\Users\itachi\Desktop\martin\Rexus.app\rexus\utils\error_handler.py:24
Function: handle_exception
---
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 10: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 10: character maps to <undefined>
